STRINGS = {
    "tr": {
        "app_title": "CRYPTODASH - KRIPTO DUNYASINA HOS GELDINIZ (V1.0)",
        "menu_header_left": " ISLEMLER",
        "menu_header_right": "HESAP ISLEMLERI",
        "m_markets": "1. Piyasalari Izle",
        "m_news": "2. Kripto Haberleri",
        "m_support": "3. Destek & FAQ",
        "m_lang": "4. Dil Degistir (TR/EN)",
        "m_login": "L. Giris Yap (Login)",
        "m_register": "R. Kayit Ol (Register)",
        "m_exit": "Q. Uygulamadan Cik",
        "choice": "Seciminiz: ",
        "invalid": "Gecersiz secim! Devam etmek icin Enter...",
        "logout": "Gule gule! CryptoDash'i tercih ettiginiz icin tesekkurler.",
        "m_trade": "1. Kolay Al-Sat",
        "m_wallet": "2. Cuzdan Detaylari",
        "m_history": "3. Islem Gecmisi",
        "m_settings": "4. Hesap Ayarlari",
        "m_logout": "O. Guvenli Cikis",
        "login_success": "Giris basarili! Yonlendiriliyorsunuz...",
        "login_fail": "Hatali kullanici adi veya sifre!",
    },
    "en": {
        "app_title": "CRYPTODASH - WELCOME TO CRYPTO WORLD (V1.0)",
        "menu_header_left": " OPERATIONS",
        "menu_header_right": "ACCOUNT OPERATIONS",
        "m_markets": "1. Watch Markets",
        "m_news": "2. Crypto News",
        "m_support": "3. Support & FAQ",
        "m_lang": "4. Change Language (TR/EN)",
        "m_login": "L. Login",
        "m_register": "R. Register",
        "m_exit": "Q. Exit Application",
        "choice": "Your Choice: ",
        "invalid": "Invalid choice! Press Enter to continue...",
        "logout": "Goodbye! Thank you for using CryptoDash.",
        "m_trade": "1. Easy Trade",
        "m_wallet": "2. Wallet Details",
        "m_history": "3. Transaction History",
        "m_settings": "4. Account Settings",
        "m_logout": "O. Logout",
        "login_success": "Login successful! Redirecting...",
        "login_fail": "Invalid username or password!",
    }
}